# Generated by Django 4.1.3 on 2022-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistanceCalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
