# Generated by Django 4.1.3 on 2022-11-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DistanceCalc', '0002_alter_distance_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='source',
            new_name='source_url',
        ),
    ]
